
package br.edu.unirn.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CadastroService", targetNamespace = "http://impl.unirn.edu.br/", wsdlLocation = "http://localhost:8080/projeto-ws/CadastroService?wsdl")
public class CadastroService
    extends Service
{

    private final static URL CADASTROSERVICE_WSDL_LOCATION;
    private final static WebServiceException CADASTROSERVICE_EXCEPTION;
    private final static QName CADASTROSERVICE_QNAME = new QName("http://impl.unirn.edu.br/", "CadastroService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/projeto-ws/CadastroService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CADASTROSERVICE_WSDL_LOCATION = url;
        CADASTROSERVICE_EXCEPTION = e;
    }

    public CadastroService() {
        super(__getWsdlLocation(), CADASTROSERVICE_QNAME);
    }

    public CadastroService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CADASTROSERVICE_QNAME, features);
    }

    public CadastroService(URL wsdlLocation) {
        super(wsdlLocation, CADASTROSERVICE_QNAME);
    }

    public CadastroService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CADASTROSERVICE_QNAME, features);
    }

    public CadastroService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CadastroService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Cadastro
     */
    @WebEndpoint(name = "CadastroImplPort")
    public Cadastro getCadastroImplPort() {
        return super.getPort(new QName("http://impl.unirn.edu.br/", "CadastroImplPort"), Cadastro.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cadastro
     */
    @WebEndpoint(name = "CadastroImplPort")
    public Cadastro getCadastroImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.unirn.edu.br/", "CadastroImplPort"), Cadastro.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CADASTROSERVICE_EXCEPTION!= null) {
            throw CADASTROSERVICE_EXCEPTION;
        }
        return CADASTROSERVICE_WSDL_LOCATION;
    }

}
