
package br.edu.unirn.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import br.edu.unirn.ObjectFactory;
import br.edu.unirn.Pessoa;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Cadastro", targetNamespace = "http://unirn.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Cadastro {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.edu.unirn.Pessoa
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperar", targetNamespace = "http://unirn.edu.br/", className = "br.edu.unirn.Recuperar")
    @ResponseWrapper(localName = "recuperarResponse", targetNamespace = "http://unirn.edu.br/", className = "br.edu.unirn.RecuperarResponse")
    public Pessoa recuperar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.edu.unirn.Pessoa
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastrar", targetNamespace = "http://unirn.edu.br/", className = "br.edu.unirn.Cadastrar")
    @ResponseWrapper(localName = "cadastrarResponse", targetNamespace = "http://unirn.edu.br/", className = "br.edu.unirn.CadastrarResponse")
    public Pessoa cadastrar(
        @WebParam(name = "arg0", targetNamespace = "")
        Pessoa arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.unirn.Pessoa>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listar", targetNamespace = "http://unirn.edu.br/", className = "br.edu.unirn.Listar")
    @ResponseWrapper(localName = "listarResponse", targetNamespace = "http://unirn.edu.br/", className = "br.edu.unirn.ListarResponse")
    public List<Pessoa> listar();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "work", targetNamespace = "http://unirn.edu.br/", className = "br.edu.unirn.Work")
    @ResponseWrapper(localName = "workResponse", targetNamespace = "http://unirn.edu.br/", className = "br.edu.unirn.WorkResponse")
    public String work(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
